version: '3.7'

services:
    client:
        build:
            target: dev
        volumes:
            - ./client:/var/www/app

    server:
        build:
            target: dev
        volumes:
            - ./server:/var/www/app
