version: '3.7'

services:
    server:
        build:
            context: ./.
            dockerfile: ./.docker/Dockerfile

    nginx:
        image: nginx:1.19-alpine
        depends_on:
            -   server
        volumes:
            - ./public:/var/www/app/public
            - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        # command: [nginx-debug, '-g', 'daemon off;']
